
const { Client, GatewayIntentBits, SlashCommandBuilder } = require('discord.js');
const ffmpeg = require('fluent-ffmpeg');
const ffmpegPath = require('ffmpeg-static');
const fs = require('fs');
const WavEncoder = require('wav-encoder');

ffmpeg.setFfmpegPath(ffmpegPath);

const TOKEN = process.env.TOKEN;

const client = new Client({
  intents: [GatewayIntentBits.Guilds],
});

client.once('ready', () => {
  console.log(`✅ Logged in as ${client.user.tag}`);
});

client.on('interactionCreate', async (interaction) => {
  if (!interaction.isChatInputCommand()) return;

  if (interaction.commandName === 'bytebeat') {
    const formula = interaction.options.getString('formula');
    const rate = interaction.options.getNumber('rate') || 44100;
    const duration = interaction.options.getNumber('duration') || 5;

// Limit sample rate and duration
const maxRate = 48000;      // max 48 kHz
const maxDuration = 30;      // max 30 seconds

const safeRate = Math.min(rate, maxRate);
const safeDuration = Math.min(duration, maxDuration);


    await interaction.deferReply();

    try {
      const totalSamples = safeRate * safeDuration;
      const samples = new Float32Array(totalSamples);

      for (let t = 0; t < totalSamples; t++) {
        let value;
        try {
          value = eval(formula);
        } catch {
          value = 0;
        }
        samples[t] = ((value % 256) - 128) / 128.0;
      }

      const audioData = { sampleRate: rate, channelData: [samples] };
      const wavBuffer = await WavEncoder.encode(audioData);
      fs.writeFileSync('bytebeat.wav', Buffer.from(wavBuffer));

      await new Promise((resolve, reject) => {
        ffmpeg('bytebeat.wav')
          .output('bytebeat.mp3')
          .on('end', resolve)
          .on('error', reject)
          .run();
      });

      await interaction.editReply({
  content: `🎵 Generated Bytebeat (rate: ${safeRate}, duration: ${safeDuration}s):\n\`\`\`${formula}\`\`\``,
  files: ['bytebeat.mp3'],
});


      fs.unlinkSync('bytebeat.wav');
      fs.unlinkSync('bytebeat.mp3');
    } catch (err) {
      console.error(err);
      interaction.editReply(`❌ Error: ${err.message}`);
    }
  }
});

client.login(TOKEN);